# 1. Usar la imagen base de Python.
FROM python:3.11-slim

# 2. Establecer el directorio de trabajo.
WORKDIR /app

# 3. Copiar y instalar dependencias de Python.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copiar el resto del código de la aplicación.
COPY . .

# 5. Exponer el puerto.
EXPOSE 8000

# 6. Comando para iniciar la aplicación.
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
